print("Hi this is Rajat Somani")
print("Hello world")
print("This is my first python program")
print("I beleive in honesty and integrity")
print("Personally I am a spiritual person")
print("Professionaly I am an Engineer MBA & Entrepreneur.")
print("I like learning new things like coding, app development, web development, and AI.")
print("I like working in management sector of technical companies")
print("I have worked with 7 different companies here in Nepal")
print("I will do something great one day with the help of my mentor")